= Balíček improutils

Pro jednodušší vypracování cvičení a domácích úkolů jsme se rozhodli vytvořit improutils - balíček s usnadňujícími a užitečnými funkcemi týkající se zpracování obrazu (dříve SVZ.ipynb).

Procházet kód jednotlivých funkcí je možné přímo v https://gitlab.fit.cvut.cz/bi-svz/improutils_package[oficiálním GitLab repozitáři] nebo ve https://github.com/ImprolabFIT/Improutils/tree/master[veřejném GitHub mirroru]. Distribuce balíčku probíhá pomocí nástroje https://pypi.org/project/improutils/[PyPI]. Dokumentace je dostupná na https://improutils.readthedocs.io/en/master/[Read the Docs].

== Použití improutils
Před použitím balíčku je nutné jej nejdříve nainstalovat do cílového prostředí. Od cvičících budete mít vždy připravený soubor requirements.txt, který by již měl obsahovat všechny potřebné závislosti. Pokud byste se jej však rozhodli instalovat po vlastní ose, stačí k tomu zavolat příkaz `pip install improutils`. Doporučujeme vždy instalovat pouze poslední verzi.

Ještě než budete volat konkrétní funkce z balíčku, je nutné naimportovat jednotlivé moduly.


== Přispívání vlastních vychytávek

Pokud se vám během kurzu podaří naimplementovat funkcionalitu, která by mohla být užitečná i pro ostatní, nebojte se o ni podělit. Každou užitečnou a zdokumentovanou implementaci rádi oceníme body aktivity.

Novou funkcionalitu je možné do balíčku dostat pomocí forknutí https://gitlab.fit.cvut.cz/bi-svz/improutils_package[improutils] repozitáře a vytvoření https://gitlab.fit.cvut.cz/bi-svz/improutils_package/merge_requests[merge requestu]. Pokud si nejste jisti, zda je vámi zamýšlená funkcionalita přínosná nebo nevíte, jak přesně přispět, neváhejte se obrátit na své cvičící.

== Hlášení chyb

Nalezli jste v nějaké funkci chybu v implementaci nebo jiný nedostatek? Pomozte nám to zlepšit a chybu nahlaste za pomocí https://gitlab.fit.cvut.cz/bi-svz/improutils_package/issues/new[vytvoření issue] na FIT GitLabu. Pokud byste rádi získali body aktivity, můžete rovnou poslat i opravu formou merge requestu.
