= Instalace nástroje pro OCR

Pro strojové čtení znaků v obrazu (tzv. OCR = optical character recognition) je zapotřebí nějaký nástroj, který to již umí. V praxi je k dispozici několik možností například -- https://github.com/tesseract-ocr/tesseract[Tesseract OCR] nebo https://cloud.google.com/vision/docs/ocr[Google Cloud Vision API].

Rozdíl mezi těmito konkrétními nástroji je markantní. Google Cloud Vision API funguje lépe, je postaven na moderních metodách hlubokých neuronových sítí, ale je dostupný pouze online přes API a po zařízení si účtu na Cloud Vision. 

Na druhou stranu Tesseract OCR je open-source, funguje offline, ale potřebuje lepší předzpracování obrazu pro správné fungování OCR. 

Zvolte si dle preferencí, na cvičení se využívá Tesseract OCR.

== Tesseract OCR
Tesseract OCR pro využití offline na PC se skládá z nástroje/knihovny v C++ (tesseract-ocr) a wrapperu pro použití v Pythonu (pytesseract). Nástroj ve skutečnosti funguje v konzoli a wrapper pro python umožňuje přidávat jak vstupní nastavení, tak vyčítat výstupy automaticky do python kódu.


=== Instalace
Instalace je převzata z odkazu https://www.pyimagesearch.com/2017/07/03/installing-tesseract-for-ocr/[zde], přeložena, upravena a rozšířena o vše potřebné pro Windows. Podrobnější instalaci včetně i dalších operačních systémů lze nalézt https://tesseract-ocr.github.io/tessdoc/Home.html[zde].

==== macOS
Pro instalaci na macu využijeme nástroj https://brew.sh[Homebrew] pro instalaci chybějících balíků.

[source]
brew install tesseract

==== Linux
Pro instalaci na Ubuntu stačí v konzoli využít klasický příkaz `apt-get`.

[source]
sudo apt-get install tesseract-ocr

Pro funkční OCR pomocí tesseract je ještě třeba mít na počítači natrénovaná data pro čtení znaků specifických jazyků. Že je tesseract má k dispozici lze ověřit příkazem:

[source]
tesseract --list-langs

Pokud příkaz nic nevypíše, lze manuálně stáhnout data třeba pro angličtinu nebo češtinu, případně pro oba jazyky. Pro Ubuntu lze použít příkazy:

[source]
sudo apt-get install tesseract-ocr-eng
sudo apt-get install tesseract-ocr-ces

==== Windows
Pro instalaci na Windows je nejlepší stáhnout si rovnou hotový instalátor z githubu https://github.com/UB-Mannheim/tesseract/wiki[UB Mannheim].

* Nainstalovat dle https://github.com/UB-Mannheim/tesseract/wiki[instrukcí]. 
** Doporučuji přidat možnost češtiny.
** Zaškrtnout `Czech` v `Additional language data (download)` 
* Zapamatovat si adresu instalace (např. C:\Program Files\Tesseract-OCR)
* Přidat odkaz na složku s tesseractem do Proměnných prostředí windows (environmental variables).
** Ukázka přidání pomocí link:images/promenne_prostredi.gif[gifu].
* Restartovat počítač (možná není nutný).
* Vyzkoušet jestli tesseract funguje v konzoli.
** Spustit konzoli `cmd`.
** Napsat příkaz `tesseract -v`

=== Použití
Pokud máte správně fungující prostředí SVZ (viz xref:tools-introduction#_postup-doma[Úvod do práce s nástroji]), je možné Tesseract OCR použít v pythonu v jupyter notebooku. 

Vyzkoušejte metodu `ocr()` v balíčku xref:improutils-package.html[improutils].

Složitější použití nástroje je vysvětleno v dokumentaci https://github.com/tesseract-ocr/tesseract/blob/master/doc/tesseract.1.asc[zde].

=== Tessdata
Tesseract OCR používá *tessdata* – natrénované modely pro rozpoznávání textu. Existuje několik oficiálních variant:

* xref:https://github.com/tesseract-ocr/tessdata_best[tessdata_best] – modely s nejvyšší přesností (větší, pomalejší). *Pro lepší kvalitu rozpoznávání se doporučuje používat tyto modely.*
* xref:https://github.com/tesseract-ocr/tessdata_fast[tessdata_fast] – modely optimalizované na rychlost (menší, rychlejší, o něco méně přesné).
* xref:https://github.com/tesseract-ocr/tessdata[tessdata] – výchozí modely dodávané s Tesseractem 

Ve výchozím nastavení Tesseract 4+ používá modely podle toho, co máte v adresáři `tessdata`. Pokud si nic speciálního nestáhnete, instalace Tesseractu obvykle obsahuje základní modely z repozitáře xref:https://github.com/tesseract-ocr/tessdata[tessdata]. Doporučujeme vyzkoušet zmiňované alternativy.
