= Virtuální prostředí

V učebně máme nainstalovaný systém Windows, všechny popsané kroky se tedy budou týkat tohoto systému. Instalace a kroky na Linuxu či Macu jsou však také popsány. 

K naší práci budeme potřebovat několik balíčku, které je potřeba nainstalovat do virtuálního prostředí. Abychom nám usnadnily život, je možné při vytváření virtuálního prostředí specifikovat soubor _spec-file.txt_, který obsahuje seznam potřebných balíčků pro tento kurz (viz jednotlivé soubory pro různé operační systémy níže). Ty se následně nainstalují při vytváření virtuálního prostředí. 

Detaily ke správě prostředí lze nalézt https://conda.io/docs/user-guide/tasks/manage-environments.html[zde].

== Postup na cvičení

* Zkontrolujte, zda je u vás na PC nainstalovaná Anaconda.
* Zapněte si `Anaconda Prompt`, ve kterém je možné využívat Python interpreter, instalovat balíčky a přepínat/modifikovat virtuální prostředí.
* Zavolejte zjednodušený skript `svz` s parametrem adresy vašeho xref:git-essentials#[naklonovaného repozitáře]
** `svz X:\_git\bi-svz`

* Pokud stále něco nepůjde, kontaktujte učitele :)


== Postup doma

* Zkontrolujte, zda je u vás na PC nainstalovaná Anaconda. Jinak si ji https://www.anaconda.com/download[stáhněte] a nainstalujte (vždy nejnovější verzi pro Python 3.8).
* Zapněte si `Anaconda Prompt`, ve kterém je možné využívat Python interpreter, instalovat balíčky a přepínat/modifikovat virtuální prostředí.

* Vytvořte virtuální prostředí pro správu balíčků knihoven s názvem `SVZ`
** `conda create --name SVZ python=3.8`
* Aktivujte vytvořené virtuální prostředí
** `activate SVZ`
* Doinstalujte potřebné knihovny pipem pomocí link:env/SVZ-pip-req.txt[SVZ-pip-req] takto:
** `pip install -r <cesta k SVZ-pip-req.txt>`


=== Nejznámější problémy a errory
WARNING: Všechna řešení je třeba dělat vždy s aktivovaným prostředím `SVZ`!

. Balíček `abc` si stěžuje na chybějící knihovnu `xyz`
** Nainstalujte příslušnou knihovnu. Na linuxu je potřeba mít nainstalovány tyto knihovny: `ffmpeg`, `libsm6`, `libxext6`, `zbar-tools`, `tesseract-ocr`

. Nefunguje rozšíření Jupyter notebooku `nbextension`. To lze opravit link:https://github.com/Jupyter-contrib/jupyter_nbextensions_configurator/issues/96#issuecomment-849050273[instalací přes condu]. 
** `conda install -c conda-forge jupyter_contrib_nbextensions`
** Potom uvnitř virtuálního prostředí nainstalovat rozšíření do uživatele.
*** `jupyter contrib nbextension install --user`

. Jupyter hází v konzoli `Kernel error` vypadající přibližně takto: 
** `win32security.DACL_SECURITY_INFORMATION access is denied` 
** Je třeba zabít kernel a před jeho opětovným spuštěním nastavit
*** `set JUPYTER_ALLOW_INSECURE_WRITES=1`
   
. Jupyter hází v konzoli chybu:
** `tornado.util.TimeoutError: Timeout`
** Řešením je downgradenout knihovnu `jupyter_client` na verzi `6.1.12`:
*** `pip install -Iv jupyter_client==6.1.12`

. Jupyter hází v konzoli chybu:
** `ImportError: DLL load failed while importing win32api: Uvedený modul nebyl nalezen.`
** Řeší se pomocí condy (pip nefunguje).
*** `conda install pywin32` 


== Důležité

* Před každým cvičením/úkolem je nutné zkontrolovat zda nepracujete ve výchozím prostředí (base). Přepnutí do prostředí SVZ:
** `conda activate SVZ`
* S aktivovaným prostředím spusťte Jupyter notebook ve složce se soubory ke kurzu
** `jupyter notebook <cesta k souborum kurzu>` 
* Otevřete úvodní notebook xref:../tutorials/files/1/jupyter-introduction.html[Práce s Jupyter notebooky] a zkontrolujte, zda všechny úvodní importy proběhnou bez problémů. 
** Pokud uvidíte hlášky typu `ImportError: No module named cv2`, musí se daný balíček doinstalovat pomocí `conda install`. V tom případě kontaktujte učitele.

NOTE: Na cvičení je zjednodušeno použitím skriptu `svz` (xref:#_postup-na-cvičení[viz výše]).


=== Poznámky

Výpis všech virtuálních prostředí lze provést pomocí `conda env list`, výpis balíčku v aktuálním prostředí `conda list`. Deaktivace aktuálního prostředí pomocí `conda deactivate`.  V případě, že chcete nějaké prostředí odstranit, tak `conda env remove --name <nazev>`. Dobrým zvykem je neinstalovat balíčky globálně (do výchozího base prostředí), ale pro každý projekt vytvořit nové virtuální prostředí. Další detaily ke správě prostředí lze nalézt https://conda.io/docs/user-guide/tasks/manage-environments.html[zde].
