= 칔vodn칤 str치nka

*Toto je ofici치ln칤 str치nka p콏edm캩tu BI-SVZ.* Naleznete zde v코echny informace t칳kaj칤c칤 se v칳uky a organizace.

Ofici치ln칤 n치stroj p콏edm캩tu pro online komunikaci student콢 a vyu캜uj칤c칤ch je **MS Teams**. Konkr칠tn칤 odkaz je https://www..cz/[ZDE] (funk캜n칤 nejpozd캩ji 21. 9. 2020).

== Anotace

Kamerov칠 syst칠my se st치vaj칤 b캩쬹ou sou캜치st칤 쬴vota t칤m, 쬰 jsou v코eobecn캩 dostupn칠. S t칤mto fenom칠nem souvis칤 i pot콏eba obrazov칠 informace zpracov치vat a vyhodnocovat. P콏edm캩t seznamuje studenty s r콢zn칳mi druhy kamerov칳ch syst칠m콢 a s 콏adou metod pro zpracov치n칤 obrazu a videa. P콏edm캩t je orientov치n na praktick칠 vyu쬴t칤 kamerov칳ch syst칠m콢 pro 콏e코en칤 칰loh z praxe, se kter칳mi se mohou absolventi setkat.

== Prerekvizity

Prerekvizitou k zaps치n칤 p콏edm캩tu je *z치kladn칤 znalost jazyka Python* pop콏칤pad캩 sebekritick칳 slib se principy jazyka Python sv칠pomoc칤 dou캜it. 

V p콏edm캩tu se vyu쮂셨치 pro pr치ci n치stroj *Jupyter notebook*, jeho znalost je k dobru, nen칤 v코ak podm칤nkou. Pr치ce v Jupyter notebooku bude vysv캩tlena.

== Aktu치ln칤 forma v칳uky
V zimn칤m semestru 2020/21 je aktu치ln칤 forma v칳uky n치sleduj칤c칤:

* P콏edn치코ky
** Kontaktn칤 v칳uka v u캜ebn캩.
** Streamovan치 z치rove켿 online p콏es MS Teams.
** Dostupn칳 z치znam na MS Teams.
* Cvi캜en칤
** Kontaktn칤 v칳uka v laborato콏i.


== Odkazy

* 游늶 https://tiny.cc/improlab_zadani_praci[Zad치n칤 prac칤]
* 游닄 xref:lectures/index#[P콏edn치코ky]
* 游닃 xref:tutorials/index#[Cvi캜en칤]
* 游늼 xref:homeworks/index#[Dom치c칤 칰koly]
* 游뱢 xref:classification/index#[Z칤sk치n칤 z치po캜tu a slo쬰n칤 zkou코ky]
* 游꿉 xref:teachers/index#[U캜itel칠]
* 游늳 https://grades.fit.cvut.cz/[Body z p콏edm캩tu]
* 游녨 https://www.facebook.com/groups/219262205443063/[Nechceme vypadnout z BI-SVZ]
* 游늱 https://timetable.fit.cvut.cz/new/courses/BI-SVZ[Rozvrh p콏edm캩tu]

