= Úvodní stránka

*Toto je oficiální stránka předmětu BI-SVZ.* Naleznete zde všechny informace týkající se výuky a organizace.

== Anotace

Kamerové systémy se stávají běžnou součástí života tím, že jsou všeobecně dostupné. S tímto fenoménem souvisí i potřeba obrazové informace zpracovávat a vyhodnocovat. Předmět seznamuje studenty s různými druhy kamerových systémů a s řadou metod pro zpracování obrazu a videa. Předmět je orientován na praktické využití kamerových systémů pro řešení úloh z praxe, se kterými se mohou absolventi setkat.

== Odkazy

* xref:lectures/index#[Přednášky]
* xref:tutorials/index#[Cvičení]
* xref:homeworks/index#[Domácí úkoly]
* xref:classification/index#[Získání zápočtu a složení zkoušky]
* xref:teachers/index#[Učitelé]
* https://grades.fit.cvut.cz/[Body z předmětu]
* https://www.facebook.com/groups/219262205443063/[Nechceme vypadnout z BI-SVZ]
* https://timetable.fit.cvut.cz/new/courses/BI-SVZ[Rozvrh předmětu]

== Důležitá oznámení

[WARNING]
====
*Deadline: neděle 16. 12. 2018 v 23:59* 

Blíží se termín odevzdání xref:homeworks/index#_harmonogram-úkolů[Úkolu 3]. Odevzdávejte přes vlastní repozitář (viz xref:homeworks/index#_odevzdání-úkolů[návod]).

_mailto:jakub.novak@fit.cvut.cz[Jakub Novák], 13. 12. 2018_
====

[WARNING]
====
*Deadline: neděle 2. 12. 2018 v 23:59* 

Blíží se termín odevzdání xref:homeworks/index#_harmonogram-úkolů[Úkolu 2]. Odevzdávejte přes vlastní repozitář (viz xref:homeworks/index#_odevzdání-úkolů[návod]).

_mailto:jakub.novak@fit.cvut.cz[Jakub Novák], 29. 11. 2018_
====

[NOTE]
====
*Nabídka bodů aktivity* 

Kdo má zájem pomoci při tvorbě návodů, prosíme o doplnění instalace prostředí pro xref:tutorials/files/1/course-tools-introduction#_systém-linux[Linux] [line-through]#a macOS#.

_mailto:jakub.novak@fit.cvut.cz[Jakub Novák], 15. 11. 2018_
====

[WARNING]
====
*Deadline: neděle 11. 11. 2018 v 23:59* 

Blíží se termín odevzdání xref:homeworks/index#_harmonogram-úkolů[Úkolu 1]. Odevzdávejte přes vlastní repozitář (viz xref:homeworks/index#_odevzdání-úkolů[návod]).

_mailto:jakub.novak@fit.cvut.cz[Jakub Novák], 9. 11. 2018_
====
