= Úvodní stránka

*Toto je oficiální stránka předmětu BI-SVZ.* Naleznete zde všechny informace týkající se výuky a organizace.

== Anotace

Kamerové systémy se stávají běžnou součástí života tím, že jsou všeobecně dostupné. S tímto fenoménem souvisí i potřeba obrazové informace zpracovávat a vyhodnocovat. Předmět seznamuje studenty s různými druhy kamerových systémů a s řadou metod pro zpracování obrazu a videa. Předmět je orientován na praktické využití kamerových systémů pro řešení úloh z praxe, se kterými se mohou absolventi setkat.

== Prerekvizity

Prerekvizitou k zapsání předmětu je *základní znalost jazyka Python* popřípadě sebekritický slib se principy jazyka Python svépomocí doučit. 

V předmětu se využívá pro práci nástroj *Jupyter notebook*, jeho znalost je k dobru, není však podmínkou. Práce v Jupyter notebooku bude vysvětlena.

== Odkazy

* https://tiny.cc/improlab_zadani_praci[Zadání prací]
* xref:lectures/index#[Přednášky]
* xref:tutorials/index#[Cvičení]
* xref:homeworks/index#[Domácí úkoly]
* xref:classification/index#[Získání zápočtu a složení zkoušky]
* xref:teachers/index#[Učitelé]
* https://grades.fit.cvut.cz/[Body z předmětu]
* https://www.facebook.com/groups/219262205443063/[Nechceme vypadnout z BI-SVZ]
* https://timetable.fit.cvut.cz/new/courses/BI-SVZ[Rozvrh předmětu]