= Novinky

== Zakončení předmětu během distanční výuky
Předmět lze zakončit distančně. Platí veškeré podmínky v link:classification/index[Hodnocení předmětu]. 

Způsob absolvování praktické části zkoušky bude upřesněn v příslušném kanálu MS Teams předmětu.

== Online výuka během časů koronaviru
Kanál MS Teams našeho předmětu je dostupný https://teams.microsoft.com/l/team/19%3a207727ff9019487a99e0b65b9e6857b8%40thread.tacv2/conversations?groupId=4c128b6f-3716-422f-85d3-88b3ef581a65&tenantId=f345c406-5268-43b0-b19f-5862fa6833f8[ZDE]. Veškeré aktuální info k výuce je tam také.

== Přednáška od odborníka z praxe
:date: 2020-03-13

Na čtvrtou přednášku přijali pozvání vedoucí oddělení Industrial Engineering , *Jan Semerák* z firmy *Vitesco Technologies Czech Republic* (dříve Continental Trutnov) a jeho kolega *Adam Šolc*, Group Leader of Test Engineering.

Osobně nám představí firmu Vitesco a dále povedou přednášku s názvem *Industry 4.0 - strojové vidění v praxi*. Máme tedy ideální možnost zjistit, jak vypadá implementace automatizace v průmyslu s požadavky na strojové vidění v praxi, společně s ukázkou přesného pozicování mikroskopu a vyhodnocení defektů objektu pomocí kamerového systému, strojového vidění a umělé inteligence.

Přednáška bude výjimečně v *místnosti A-1455*, čas stejný 9:15 - 10:45. Můžete se jí zúčastnit i když nemáte zapsán předmět BI-SVZ. Pozor místnost není nafukovací ;-)

S firmou Vitesco Technologies Czech Republic se laboratoř https://improlab.fit.cvut.cz[ImproLab] aktivně podílí na projektech z praxe, do kterých se mohou připojit i studenti.

== Nabídka bodů aktivity
:date: 2020-02-18

Kdo má zájem pomoci při tvorbě návodů, prosíme o otestování instalace prostředí pro xref:tutorials/course-tools-introduction#_systém-linux[Linux]. Konkrétně se jedná o Ubuntu. Jeho instalaci najdete na GITu v repu BI-SVZ v separátní větvi __linux-env-spec-file__.