= Novinky

== Vítejte v zimním semestru
:date: 2026-09-21
Vážení studenti, vítejte v semestru B261. Stránky předmětu byly aktualizovány na nový harmonogram:

* Přednášky probíhají v úterý 9:15–10:45 v učebně JP:B-571, první přednáška je *22. 9. 2026*. Přednášky 1–4 vede David Kramný, zbývající přednášky vede Marcel Jiřina.
* Cvičení začínají ve čtvrtek *24. 9. 2026* v laboratoři ImproLab (A-1256).
* *3. 11. 2026* proběhne místo běžné přednášky zvaná přednáška odborníka z praxe, podrobnosti upřesníme.
* *17. 11. 2026* je státní svátek, přednáška odpadá.
* Domácí úkoly zveřejňujeme v pátek po druhém cvičení a nově máte na každý *14 dní* namísto dřívějších 12 - termín odevzdání jsme posunuli ze středy na pátek. Termíny jsou v sekci xref:homeworks/index#[Domácí úkoly].
* Tým cvičících posílil o Honzu Soukup!
* Balíček https://gitlab.fit.cvut.cz/bi-svz/improutils_package[improutils] nově staví na *OpenCV 5*.
* xref:exam/index#[OpenLab] před praktickou zkouškou se v minulém semestru osvědčil, zachováváme ho pro následující semestry.
* Otázky teoretické části zkoušky budou během semestru upravuveny a rozšířeny, aby byly jednoznačné. 
* U praktické části zkoušky budou zadání formulována explicitněji než dosud - přesně uvedeme, co od vás očekáváme, aby nevznikaly nejasnosti. 

Těšíme se na společný semestr!

== Vítejte v zimním semestru 
:date: 2025-11-24
====================================================
Vážení studenti, dne *2. prosince 2025 odpadá výuka*.
====================================================

== Vítejte v zimním semestru 
:date: 2025-09-24
Vážení studenti, kurz prošel refaktorem a celkovou aktualizací, která zohledňuje podněty z ankety za semestr B242. Mezi hlavní změny patří:

* Aktualizace stránek kurzu, oprava chyb a přizpůsobení obsahu aktuálním změnám v předmětu.
* Balíček https://gitlab.fit.cvut.cz/bi-svz/improutils_package[improutils] byl rozšířen tak, aby cvičení nevyžadovala volání souboru `library.ipynb`. Dále byly odstraněny implicitní importy a sjednoceny docstringy s celkovým lintingem balíčku.
* Postupně budou zveřejňovány nové nahrávky přednášek, odpovídajících změně přednášejících.
* Postupně budou zveřejňovány cvičení, které nyní nebudou používat wildcard importy a soubor `library.ipynb`.
* Byla připravena nová zkoušková zadání pro praktickou část, podrobnosti budou oznámeny v průběhu semestru.

Věříme, že tato vylepšení odpovídají vašim připomínkám a přispějí ke zvýšení kvality kurzu.


== Refaktor kurzu BI-SVZ
:date: 2023-02-27
Vážení studenti, dnes byl dokončen velký refaktor kurzu reflektující podněty v anketě za semestr B221. Byly provedeny tyto aktivity:

* Úvodní stránka předmětu přehledně ukazuje co je cílem předmětu, co se student naučí a co se nenaučí, aby se zabránilo případným mylným očekáváním.
* Byly dodány linky na předměty napříč pražskými univerzitami, které poskytují další znalosti a vhled do probrané problematiky.
* Byla dodána stránka s dalšími informacemi ke zkoušce, které se běžně vyskytovaly v kanálu předmětu na MS Teams.
* Materiály a návody byly přesunuty do přehlednější struktury na vlastní stránku.

* Byla doplněna dokumentace knihovny improutils a vložena nová verze na PyPi (1.1.12).
* Byla zkontrolovány jupyter notebooky cvičení kvůli chybám a opraveny.
* Bylo navrženo a přidáno nové cvičení na práci se světly.

* Byly vyhodnoceny kvízy v teoretické části zkoušky a nalezeny rozporuplné příklady z pohledu odpovědí.
* Byly upraveny špatně odpovídané možnosti nalezených příkladů tak, aby byly jednoznačněji pochopitelné.

Věříme, že všechna vylepšení reflektují podněty v anketě a povedou ke zvýšení kvality kurzu.


== Vítejte v letním semestru
:date: 2021-02-15
Vážení studenti, předmět bude opět probíhat čistě distančně 😟 Během semestru se však počítá s organizací několika individuálních laboratorních cvičení pro menší počet lidí, abyste si alespoň trochu osahali HW a sžili se s ním.

Jinak všechny vítáme a těšíme se na společný semestr!


== Poslední cvičení prezenčně
:date: 2020-12-17
Cvičení dne 17. 12. 2020 bude probíhat prezenčně v ImproLabu (A-1256). Využijeme příležitosti pro seznámení se s hardware potřebným pro absolvování praktické zkoušky - kamery, objektivy, světla a kalibrace kamery.


== Zkoušky v LS 2019/2020 (B-192)
Úprava pokynů a doplnění ke konání zkoušek je k dispozici v https://teams.microsoft.com/l/message/19:207727ff9019487a99e0b65b9e6857b8@thread.tacv2/1588675409413?tenantId=f345c406-5268-43b0-b19f-5862fa6833f8&groupId=4c128b6f-3716-422f-85d3-88b3ef581a65&parentMessageId=1588675409413&teamName=Team-Predmet-B192-BI-SVZ&channelName=Obecn%C3%A9&createdTime=1588675409413[kanálu na MS Teams].


== Možnost zapojení se do úloh s Termokamerami
Aktuální situace ohledně koronaviru vyžaduje často využití termokamer pro *měření teploty člověka na vstupu do budovy*. 

V případě, že by to někoho zajímalo a rád by se podílel na tvorbě takové úlohy, tak ho přivítáme.

Více info v https://teams.microsoft.com/l/message/19:207727ff9019487a99e0b65b9e6857b8@thread.tacv2/1585813165598?tenantId=f345c406-5268-43b0-b19f-5862fa6833f8&groupId=4c128b6f-3716-422f-85d3-88b3ef581a65&parentMessageId=1585813165598&teamName=Team-Predmet-B192-BI-SVZ&channelName=Obecn%C3%A9&createdTime=1585813165598[odkazu na MS teams].

== Zakončení předmětu během distanční výuky
Předmět lze zakončit distančně. Platí veškeré podmínky v link:classification/index[Hodnocení předmětu]. 

Způsob absolvování praktické části zkoušky bude upřesněn v příslušném kanálu MS Teams předmětu.

== Online výuka během časů koronaviru
Kanál MS Teams našeho předmětu je dostupný https://teams.microsoft.com/l/team/19%3a207727ff9019487a99e0b65b9e6857b8%40thread.tacv2/conversations?groupId=4c128b6f-3716-422f-85d3-88b3ef581a65&tenantId=f345c406-5268-43b0-b19f-5862fa6833f8[ZDE]. Veškeré aktuální info k výuce je tam také.

== Přednáška od odborníka z praxe
:date: 2020-03-13

Na čtvrtou přednášku přijali pozvání vedoucí oddělení Industrial Engineering , *Jan Semerák* z firmy *Vitesco Technologies Czech Republic* (dříve Continental Trutnov) a jeho kolega *Adam Šolc*, Group Leader of Test Engineering.

Osobně nám představí firmu Vitesco a dále povedou přednášku s názvem *Industry 4.0 - strojové vidění v praxi*. Máme tedy ideální možnost zjistit, jak vypadá implementace automatizace v průmyslu s požadavky na strojové vidění v praxi, společně s ukázkou přesného pozicování mikroskopu a vyhodnocení defektů objektu pomocí kamerového systému, strojového vidění a umělé inteligence.

Přednáška bude výjimečně v *místnosti A-1455*, čas stejný 9:15 - 10:45. Můžete se jí zúčastnit i když nemáte zapsán předmět BI-SVZ. Pozor místnost není nafukovací ;-)

S firmou Vitesco Technologies Czech Republic se laboratoř https://improlab.fit.cvut.cz[ImproLab] aktivně podílí na projektech z praxe, do kterých se mohou připojit i studenti.

== Nabídka bodů aktivity
:date: 2020-02-18

Kdo má zájem pomoci při tvorbě návodů, prosíme o otestování instalace prostředí pro xref:tutorials/course-tools-introduction#_systém-linux[Linux]. Konkrétně se jedná o Ubuntu. Jeho instalaci najdete na GITu v repu BI-SVZ v separátní větvi __linux-env-spec-file__.