= Novinky

== V칤tejte v zimn칤m semestru 
:date: 2025-09-24
V치쬰n칤 studenti, kurz pro코el refaktorem a celkovou aktualizac칤, kter치 zohled켿uje podn캩ty z ankety za semestr B242. Mezi hlavn칤 zm캩ny pat콏칤:

* Aktualizace str치nek kurzu, oprava chyb a p콏izp콢soben칤 obsahu aktu치ln칤m zm캩n치m v p콏edm캩tu.
* Bal칤캜ek https://gitlab.fit.cvut.cz/bi-svz/improutils_package[improutils] byl roz코칤콏en tak, aby cvi캜en칤 nevy쬬dovala vol치n칤 souboru `library.ipynb`. D치le byly odstran캩ny implicitn칤 importy a sjednoceny docstringy s celkov칳m lintingem bal칤캜ku.
* Postupn캩 budou zve콏ej켿ov치ny nov칠 nahr치vky p콏edn치코ek, odpov칤daj칤c칤ch zm캩n캩 p콏edn치코ej칤c칤ch.
* Postupn캩 budou zve콏ej켿ov치ny cvi캜en칤, kter칠 nyn칤 nebudou pou쮂셨at implicitn칤 importy a soubor `library.ipynb`.
* Byla p콏ipravena nov치 zkou코kov치 zad치n칤 pro praktickou 캜치st, podrobnosti budou ozn치meny v pr콢b캩hu semestru.

V캩콏칤me, 쬰 tato vylep코en칤 odpov칤daj칤 va코im p콏ipom칤nk치m a p콏isp캩j칤 ke zv칳코en칤 kvality kurzu.


== Refaktor kurzu BI-SVZ
:date: 2023-02-27
V치쬰n칤 studenti, dnes byl dokon캜en velk칳 refaktor kurzu reflektuj칤c칤 podn캩ty v anket캩 za semestr B221. Byly provedeny tyto aktivity:

* 칔vodn칤 str치nka p콏edm캩tu p콏ehledn캩 ukazuje co je c칤lem p콏edm캩tu, co se student nau캜칤 a co se nenau캜칤, aby se zabr치nilo p콏칤padn칳m myln칳m o캜ek치v치n칤m.
* Byly dod치ny linky na p콏edm캩ty nap콏칤캜 pra쬽k칳mi univerzitami, kter칠 poskytuj칤 dal코칤 znalosti a vhled do probran칠 problematiky.
* Byla dod치na str치nka s dal코칤mi informacemi ke zkou코ce, kter칠 se b캩쬹캩 vyskytovaly v kan치lu p콏edm캩tu na MS Teams.
* Materi치ly a n치vody byly p콏esunuty do p콏ehledn캩j코칤 struktury na vlastn칤 str치nku.

* Byla dopln캩na dokumentace knihovny improutils a vlo쬰na nov치 verze na PyPi (1.1.12).
* Byla zkontrolov치ny jupyter notebooky cvi캜en칤 kv콢li chyb치m a opraveny.
* Bylo navr쬰no a p콏id치no nov칠 cvi캜en칤 na pr치ci se sv캩tly.

* Byly vyhodnoceny kv칤zy v teoretick칠 캜치sti zkou코ky a nalezeny rozporupln칠 p콏칤klady z pohledu odpov캩d칤.
* Byly upraveny 코patn캩 odpov칤dan칠 mo쬹osti nalezen칳ch p콏칤klad콢 tak, aby byly jednozna캜n캩ji pochopiteln칠.

V캩콏칤me, 쬰 v코echna vylep코en칤 reflektuj칤 podn캩ty v anket캩 a povedou ke zv칳코en칤 kvality kurzu.


== V칤tejte v letn칤m semestru
:date: 2021-02-15
V치쬰n칤 studenti, p콏edm캩t bude op캩t prob칤hat 캜ist캩 distan캜n캩 游 B캩hem semestru se v코ak po캜칤t치 s organizac칤 n캩kolika individu치ln칤ch laboratorn칤ch cvi캜en칤 pro men코칤 po캜et lid칤, abyste si alespo켿 trochu osahali HW a s쬴li se s n칤m.

Jinak v코echny v칤t치me a t캩코칤me se na spole캜n칳 semestr!


== Posledn칤 cvi캜en칤 prezen캜n캩
:date: 2020-12-17
Cvi캜en칤 dne 17. 12. 2020 bude prob칤hat prezen캜n캩 v ImproLabu (A-1256). Vyu쬴jeme p콏칤le쬴tosti pro sezn치men칤 se s hardware pot콏ebn칳m pro absolvov치n칤 praktick칠 zkou코ky - kamery, objektivy, sv캩tla a kalibrace kamery.


== Zkou코ky v LS 2019/2020 (B-192)
칔prava pokyn콢 a dopln캩n칤 ke kon치n칤 zkou코ek je k dispozici v https://teams.microsoft.com/l/message/19:207727ff9019487a99e0b65b9e6857b8@thread.tacv2/1588675409413?tenantId=f345c406-5268-43b0-b19f-5862fa6833f8&groupId=4c128b6f-3716-422f-85d3-88b3ef581a65&parentMessageId=1588675409413&teamName=Team-Predmet-B192-BI-SVZ&channelName=Obecn%C3%A9&createdTime=1588675409413[kan치lu na MS Teams].


== Mo쬹ost zapojen칤 se do 칰loh s Termokamerami
Aktu치ln칤 situace ohledn캩 koronaviru vy쬬duje 캜asto vyu쬴t칤 termokamer pro *m캩콏en칤 teploty 캜lov캩ka na vstupu do budovy*. 

V p콏칤pad캩, 쬰 by to n캩koho zaj칤malo a r치d by se pod칤lel na tvorb캩 takov칠 칰lohy, tak ho p콏iv칤t치me.

V칤ce info v https://teams.microsoft.com/l/message/19:207727ff9019487a99e0b65b9e6857b8@thread.tacv2/1585813165598?tenantId=f345c406-5268-43b0-b19f-5862fa6833f8&groupId=4c128b6f-3716-422f-85d3-88b3ef581a65&parentMessageId=1585813165598&teamName=Team-Predmet-B192-BI-SVZ&channelName=Obecn%C3%A9&createdTime=1585813165598[odkazu na MS teams].

== Zakon캜en칤 p콏edm캩tu b캩hem distan캜n칤 v칳uky
P콏edm캩t lze zakon캜it distan캜n캩. Plat칤 ve코ker칠 podm칤nky v link:classification/index[Hodnocen칤 p콏edm캩tu]. 

Zp콢sob absolvov치n칤 praktick칠 캜치sti zkou코ky bude up콏esn캩n v p콏칤slu코n칠m kan치lu MS Teams p콏edm캩tu.

== Online v칳uka b캩hem 캜as콢 koronaviru
Kan치l MS Teams na코eho p콏edm캩tu je dostupn칳 https://teams.microsoft.com/l/team/19%3a207727ff9019487a99e0b65b9e6857b8%40thread.tacv2/conversations?groupId=4c128b6f-3716-422f-85d3-88b3ef581a65&tenantId=f345c406-5268-43b0-b19f-5862fa6833f8[ZDE]. Ve코ker칠 aktu치ln칤 info k v칳uce je tam tak칠.

== P콏edn치코ka od odborn칤ka z praxe
:date: 2020-03-13

Na 캜tvrtou p콏edn치코ku p콏ijali pozv치n칤 vedouc칤 odd캩len칤 Industrial Engineering , *Jan Semer치k* z firmy *Vitesco Technologies Czech Republic* (d콏칤ve Continental Trutnov) a jeho kolega *Adam 맖lc*, Group Leader of Test Engineering.

Osobn캩 n치m p콏edstav칤 firmu Vitesco a d치le povedou p콏edn치코ku s n치zvem *Industry 4.0 - strojov칠 vid캩n칤 v praxi*. M치me tedy ide치ln칤 mo쬹ost zjistit, jak vypad치 implementace automatizace v pr콢myslu s po쬬davky na strojov칠 vid캩n칤 v praxi, spole캜n캩 s uk치zkou p콏esn칠ho pozicov치n칤 mikroskopu a vyhodnocen칤 defekt콢 objektu pomoc칤 kamerov칠ho syst칠mu, strojov칠ho vid캩n칤 a um캩l칠 inteligence.

P콏edn치코ka bude v칳jime캜n캩 v *m칤stnosti A-1455*, 캜as stejn칳 9:15 - 10:45. M콢쬰te se j칤 z칰캜astnit i kdy nem치te zaps치n p콏edm캩t BI-SVZ. Pozor m칤stnost nen칤 nafukovac칤 ;-)

S firmou Vitesco Technologies Czech Republic se laborato콏 https://improlab.fit.cvut.cz[ImproLab] aktivn캩 pod칤l칤 na projektech z praxe, do kter칳ch se mohou p콏ipojit i studenti.

== Nab칤dka bod콢 aktivity
:date: 2020-02-18

Kdo m치 z치jem pomoci p콏i tvorb캩 n치vod콢, pros칤me o otestov치n칤 instalace prost콏ed칤 pro xref:tutorials/course-tools-introduction#_syst칠m-linux[Linux]. Konkr칠tn캩 se jedn치 o Ubuntu. Jeho instalaci najdete na GITu v repu BI-SVZ v separ치tn칤 v캩tvi __linux-env-spec-file__.