= Novinky

== V칤tejte v letn칤m semestru
:date: 2021-02-15
V치쬰n칤 studenti, p콏edm캩t bude op캩t prob칤hat 캜ist캩 distan캜n캩 游 B캩hem semestru se v코ak po캜칤t치 s organizac칤 n캩kolika individu치ln칤ch laboratorn칤ch cvi캜en칤 pro men코칤 po캜et lid칤, abyste si alespo켿 trochu osahali HW a s쬴li se s n칤m.

Jinak v코echny v칤t치me a t캩코칤me se na spole캜n칳 semestr!


== Posledn칤 cvi캜en칤 prezen캜n캩
:date: 2020-12-17
Cvi캜en칤 dne 17. 12. 2020 bude prob칤hat prezen캜n캩 v ImproLabu (A-1256). Vyu쬴jeme p콏칤le쬴tosti pro sezn치men칤 se s hardware pot콏ebn칳m pro absolvov치n칤 praktick칠 zkou코ky - kamery, objektivy, sv캩tla a kalibrace kamery.


== Zkou코ky v LS 2019/2020 (B-192)
칔prava pokyn콢 a dopln캩n칤 ke kon치n칤 zkou코ek je k dispozici v https://teams.microsoft.com/l/message/19:207727ff9019487a99e0b65b9e6857b8@thread.tacv2/1588675409413?tenantId=f345c406-5268-43b0-b19f-5862fa6833f8&groupId=4c128b6f-3716-422f-85d3-88b3ef581a65&parentMessageId=1588675409413&teamName=Team-Predmet-B192-BI-SVZ&channelName=Obecn%C3%A9&createdTime=1588675409413[kan치lu na MS Teams].


== Mo쬹ost zapojen칤 se do 칰loh s Termokamerami
Aktu치ln칤 situace ohledn캩 koronaviru vy쬬duje 캜asto vyu쬴t칤 termokamer pro *m캩콏en칤 teploty 캜lov캩ka na vstupu do budovy*. 

V p콏칤pad캩, 쬰 by to n캩koho zaj칤malo a r치d by se pod칤lel na tvorb캩 takov칠 칰lohy, tak ho p콏iv칤t치me.

V칤ce info v https://teams.microsoft.com/l/message/19:207727ff9019487a99e0b65b9e6857b8@thread.tacv2/1585813165598?tenantId=f345c406-5268-43b0-b19f-5862fa6833f8&groupId=4c128b6f-3716-422f-85d3-88b3ef581a65&parentMessageId=1585813165598&teamName=Team-Predmet-B192-BI-SVZ&channelName=Obecn%C3%A9&createdTime=1585813165598[odkazu na MS teams].

== Zakon캜en칤 p콏edm캩tu b캩hem distan캜n칤 v칳uky
P콏edm캩t lze zakon캜it distan캜n캩. Plat칤 ve코ker칠 podm칤nky v link:classification/index[Hodnocen칤 p콏edm캩tu]. 

Zp콢sob absolvov치n칤 praktick칠 캜치sti zkou코ky bude up콏esn캩n v p콏칤slu코n칠m kan치lu MS Teams p콏edm캩tu.

== Online v칳uka b캩hem 캜as콢 koronaviru
Kan치l MS Teams na코eho p콏edm캩tu je dostupn칳 https://teams.microsoft.com/l/team/19%3a207727ff9019487a99e0b65b9e6857b8%40thread.tacv2/conversations?groupId=4c128b6f-3716-422f-85d3-88b3ef581a65&tenantId=f345c406-5268-43b0-b19f-5862fa6833f8[ZDE]. Ve코ker칠 aktu치ln칤 info k v칳uce je tam tak칠.

== P콏edn치코ka od odborn칤ka z praxe
:date: 2020-03-13

Na 캜tvrtou p콏edn치코ku p콏ijali pozv치n칤 vedouc칤 odd캩len칤 Industrial Engineering , *Jan Semer치k* z firmy *Vitesco Technologies Czech Republic* (d콏칤ve Continental Trutnov) a jeho kolega *Adam 맖lc*, Group Leader of Test Engineering.

Osobn캩 n치m p콏edstav칤 firmu Vitesco a d치le povedou p콏edn치코ku s n치zvem *Industry 4.0 - strojov칠 vid캩n칤 v praxi*. M치me tedy ide치ln칤 mo쬹ost zjistit, jak vypad치 implementace automatizace v pr콢myslu s po쬬davky na strojov칠 vid캩n칤 v praxi, spole캜n캩 s uk치zkou p콏esn칠ho pozicov치n칤 mikroskopu a vyhodnocen칤 defekt콢 objektu pomoc칤 kamerov칠ho syst칠mu, strojov칠ho vid캩n칤 a um캩l칠 inteligence.

P콏edn치코ka bude v칳jime캜n캩 v *m칤stnosti A-1455*, 캜as stejn칳 9:15 - 10:45. M콢쬰te se j칤 z칰캜astnit i kdy nem치te zaps치n p콏edm캩t BI-SVZ. Pozor m칤stnost nen칤 nafukovac칤 ;-)

S firmou Vitesco Technologies Czech Republic se laborato콏 https://improlab.fit.cvut.cz[ImproLab] aktivn캩 pod칤l칤 na projektech z praxe, do kter칳ch se mohou p콏ipojit i studenti.

== Nab칤dka bod콢 aktivity
:date: 2020-02-18

Kdo m치 z치jem pomoci p콏i tvorb캩 n치vod콢, pros칤me o otestov치n칤 instalace prost콏ed칤 pro xref:tutorials/course-tools-introduction#_syst칠m-linux[Linux]. Konkr칠tn캩 se jedn치 o Ubuntu. Jeho instalaci najdete na GITu v repu BI-SVZ v separ치tn칤 v캩tvi __linux-env-spec-file__.