= Hodnocení

== Body ze cvičení a získání zápočtu

* Pro získání zápočtu je nutné a postačující ze cvičení získat alespoň *25 bodů* z 50 možných.
* Za každé cvičení je možné získat *2 body*.
* Budou zadány *4 úkoly* celkem za *26 bodů*. 
* Během semestru je též možné získat až *10 prémiových bodů* za nadprůměrnou aktivitu a práci nad rámec povinností. Prémiové body neslouží k zisku zápočtu, vylepšují celkové hodnocení po zkoušce.
* Na cvičení se nepíší *žádné testy*.
* *Docházka* na cvičení *se eviduje*, nemá však vliv na hodnocení.
* Předmět není možné absolvovat bez získání zápočtu.

== Podmínky pro složení záverečné zkoušky

* K závěrečné zkoušce je možné přístoupit *pouze se získaným zápočtem*.
* Závěrečná zkouška se skládá z *dvou povinných částí*. Bez úspěšného složení teoretické zkoušky nelze přístoupit ke zkoušce praktické.
* Z obou částí zkoušky je nutné získat *alespoň* tolik bodů, kolik je minimální hranice.
* Obě části zkoušky je možné absolvovat v ten samý den, pokud bude splněno výše zmíněné.

=== Teoretická část

* Pro úspěšné absolvování teoretické části je nutné získat *alespoň 10 bodů* z možných 20.
* Teoretická část probíhá formou *multichoice testu*. 
** V případě zvolení všech správných odpovědí je otázka považována za zodpovězenou (+ 1 bod).
** V případě zvolení pouze jediné odpovědi špatně, je otázka považována za skoro správně (+ 0,5 bodu).
** V případě zodpovězení všech odpovědí špatně je otázka považována za hrubou neznalost (- 1 bod).
** V ostatních případech je otázka považována za nezodpovězenou (0 bodů).


=== Praktická část

* Pro úspěšné absolvování praktické části je nutné získat *alespoň 15 bodů* z možných 30.
* Praktická část se skládá ze samostatného vypracování úlohy podobného formátu, jako jsou příklady na cvičení. Student využije znalosti HW i SW, získané během semetru.


== Ústní gamble
* Pro vylepšení bodového zisku je možné *dobrovolně* absolvovat tzv. "ústní gamble" formou *ústního dozkoušení*.
* Tímto způsobem je možné až *zdvojnásobit* množství *bodů aktivity* získaných během semestru.

* Algoritmus:
** Podmínkou účasti je *úspěšné absolvování* závěrečné zkoušky.
** Podmínkou účasti je *minimální zisk 1 prémiového bodu* za aktivitu během semestru.
** Svou účastí student *potvrzuje*, že se s okamžitou platností *dobrovolně vzdává všech* svých prémiových bodů aktivity.
** Student je ústně zkoušen a je mu pokládána *1 otázka za každý 1 bod aktivity*, kterého se svou účastí dobrovolně vzdal. (Není vyloučeno, že otázka se může skládat z více podotázek.)
** Každá otázka může být zodpovězena buď správně (+ 1 bod) nebo špatně (0 bodů).
** Pokud student odpoví na nějakou otázku *špatně*, ústní gamble *okamžitě končí* a již mu nejsou pokládány další otázky (i když by na ně podle původního počtu bodů aktivity měl mít nárok).
** Na konci je *počet získaných bodů* z ústního dozkoušení *vynásoben dvěma*.


== Celkové hodnocení

* Celkově je možné získat v součtu až *120 bodů*.
** 50 bodů za cvičení a domácí úkoly.
** 50 bodů ze zkoušky. 
** 10 prémiových bodů za aktivitu nad rámec povinností.
** 10 bodů získaných absolvováním ústního gamblu.
* Výsledná známka je dána bodovým ziskem celkem dle tabulky níže.
* V případě dosažení necelého počtu bodů se výsledek konečné známky prostě zaokrouhluje.


.Bodové hodnocení
[width="75%", options="header"]
|===
| Známka | Bodové  rozmezí | Slovní  hodnocení 
| A      | 90 a více       | výborně           
| B      | 80 - 89         | velmi dobře       
| C      | 70 - 79         | dobře             
| D      | 60 - 69         | uspokojivě        
| E      | 50 - 59         | dostatečně        
| F      | méně než 50     | nedostatečně      
|===

Hodnocení se řídí https://www.cvut.cz/vnitrni-predpisy[Studijním a zkušebním řádem ČVUT].