= Hodnocení

== Body ze cvičení a získání zápočtu

* Pro získání zápočtu je nutné a postačující ze cvičení získat alespoň *25 bodů* z 50 možných.
* Za každé cvičení je možné získat *2 body*.
* Budou zadány *4 úkoly* celkem za *26 bodů*. 
* Během semestru je též možné získat až *10 prémiových bodů* za nadprůměrnou aktivitu a práci nad rámec povinností.
* Na cvičení se nepíšou *žádné testy*.
* *Docházka* na cvičení *se eviduje*, nemá však vliv na hodnocení.
* Předmět není možné absolvovat bez získání zápočtu.

== Podmínky pro složení záverečné zkoušky

* K závěrečné zkoušce je možné přístoupit *pouze se získaným zápočtem*.
* Závěrečná zkouška se skládá z *dvou povinných částí*. Bez úspěšného složení teoretické zkoušky nelze přístoupit ke zkoušce praktické.
* Z obou částí zkoušky je nutné získat více bodů, než je minimální hranice.

=== Teoretická část

* Pro úspěšné absolvování teoretické části je nutné získat *alespoň 10 bodů* z možných 20.
* Teoretická část probíhá formou *multichoice testu*. V případě zvolení všech správných odpovědí je otázka považována za zodpovězenou, v ostatních případech ne.
* Za předpokladu splnění minimální hranice, je možné k vylepšení bodového zisku využít *dobrovolného ústního dozkoušení*.

=== Praktická část

* Pro úspěšné absolvování praktické části je nutné získat *alespoň 15 bodů* z možných 30.
* Praktická část se bude skládat z vypracování úlohy podobného formátu, jako jsou příklady na cvičení.

== Celkové hodnocení

* Celkově je možné získat v součtu až *110 bodů*.
** 50 bodů za cvičení a domácí úkoly.
** 50 bodů ze zkoušky. 
** 10 prémiových bodů za aktivitu nad rámec povinností.
* Výsledná známka je dána bodovým ziskem celkem dle tabulky níže.

.Bodové hodnocení
[width="50%", options="header"]
|===
| Známka | Bodové  rozmezí | Slovní  hodnocení 
| A      | 90 a více       | výborně           
| B      | 80 - 89         | velmi dobře       
| C      | 70 - 79         | dobře             
| D      | 60 - 69         | uspokojivě        
| E      | 50 - 59         | dostatečně        
| F      | méně než 50     | nedostatečně      
|===

Hodnocení se řídí https://www.cvut.cz/sites/default/files/content/7e72349e-3ea5-4693-9853-5147f1238481/cs/20180718-studijni-a-zkusebni-rad-pro-studenty-cvut.pdf[Studijním a zkušebním řádem ČVUT].