= 5. Informace ke zkoušce

// Definice proměnných datumů
include::../vars.adoc[]

Předmět je z pohledu obsahu a množství látky hodnocen jako jeden z těch těžších. Zisk znalostí strojového vidění v průmyslu je nelehké a látka je náročná. 

Stránka upřesňuje formu a průběh zkoušky s cílem lepšího přiblížení studentům.

NOTE: Konkrétní požadavky na absolvování předmětu (počet bodů atd.) jsou dostupné na stránce xref:../classification/index#[Hodnocení].

== ℹ️ Rozdělení a zdůvodnění

Zkouška je rozdělena na *teoretickou* a *praktickou* část. 

Teoretická část si klade za cíl vyzkoušet studenta ze znalostí nabytých na přednáškách formou multiple choice testu.

Praktická část si klade za cíl vyzkoušet znalosti nabyté na cvičeních formou typické (průmyslové) úlohy z praxe.

== 💯 Průběh zkoušky

Teoretická část zkoušky probíhá *prezenčně* v ImproLabu (A-1256) v nástroji https://marast.fit.cvut.cz[MARAST].

* V KOSu budou vypsány termíny formou jednorázových akcí.
* Student se musí na akci přihlásit.
* Kvíz bude zaheslován vždy na konkrétní termín.
* Heslo se dozví student od zkoušejícího v místnosti.

Praktická část zkoušky probíhá *prezenčně* v ImproLabu (A-1256).

* V KOSu budou vypsány termíny formou zkouškových termínů.
* Student se musí na termín přihlásit.

NOTE: https://kos.cvut.cz/terms[Webový KOS] obsahuje všechny termíny přehledně na jedné straně - jak regulérní termíny, tak jednorázové akce.

*Individuálně* budou řešeny případy nemožnosti přijít prezenčně (např. student je v zahraničí a neexistuje způsob se na FIT dostat). V takovém případě kontaktujte xref:../teachers/index#[Davida Kramného] na MS Teams.

== 🛠️ Informace k Praktické části

Praktická zkouška probíhá *prezenčně* v ImproLabu (A-1256) na počítačích v učebně (není možné využívat vlastní PC). Skládá se ze **samostatného** vypracování několika dílčích úloh podobného formátu, jako jsou příklady na cvičení. Student využije znalosti HW i SW, získané během semestru.

* Student vytváří vlastní Jupyter notebook, který odevzdává.
* Student má k dispozici internet pro možné hledání oprav chyb v Pythonu, dokumentaci k OpenCV funkcím a dokumentaci k Improututils.
* Internet není povolen pro přístup na courses, gitlab, pro komunikaci s chatboty či jinými AI nástroji (ChatGPT, Copilot). 
* Obsah zkoušky (vypracovaný notebook + snímky) je zakázáno vynášet a distribuovat.
* Náhledy zkoušek budou k dispozici po předchozí domluvě se zkoušejícím.
* Oproti předchozím semestrům **není** povoleno si přinést vlastní pomocný notebook!

== 👁️ OpenLab
Studenti mají před praktickou zkouškou možnost využít laboratoř ImproLab k samostatnému vyzkoušení a procvičení libovolných úloh, technik apod., se kterými se během semestru setkali. Tento prostor je určen k upevnění znalostí, otestování vlastních nápadů i doplnění případných nejasností. K dispozici je veškerý laboratorní hardware a vybavení, které mohou studenti volně využít. Doporučujeme tuto příležitost nepromarnit a přijít si vše prakticky vyzkoušet.

Termíny pro přístup do laboratoře jsou vypsány v *KOSu jako jednorázové akce*. Kapacita jednoho termínu je *10 studentů*. Je možné přijít i ve dvojici, v takovém případě se prosím zapisuje *pouze jeden z dvojice*. Zápis slouží především k orientaci a k tomu, aby v uvedených časech byl k dispozici někdo, kdo vám může *zodpovědět případné dotazy*.

Pokud vám žádný z vypsaných termínů nevyhovuje, neváhejte napsat Davidovi Kramnému a domluvit si *individuální termín*.

