= Dom치c칤 칰koly

V semestru budou postupn캩 zad치ny celkem *4 jednoduch칠 domac칤 칰koly*. 칔koly zad치v치me, abychom ov캩콏ili va코e pochopen칤 prob칤ran칠 l치tky. Pro v코echny, kte콏칤 porozum칤 l치tce probran칠 na cvi캜en칤, se jedn치 maxim치ln캩 o dvou hodinovou z치le쬴tost. 칔koly voln캩 *navazuj칤 na 칰lohy z cvi캜en칤*.

칔koly nejsou povinn칠, *tvo콏칤 v코ak p콏es polovinu mo쬹칳ch bod콢 ze semestru* (26 bod콢 z celkov칳ch 50). P콏칤pom칤n치me, 쬰 k z칤sk치n칤 z치po캜tu je nutn칠 za cvi캜en칤 z칤skat *minim치ln캩 25 bod콢*, podrobnosti viz sekce xref:../classification/index#[hodnocen칤].

Na za캜치tku ka쬯칠ho cvi캜en칤 bude prostor na dotazy t칳kaj칤c칤 se aktu치ln칤ho zadan칠ho 칰kolu. C칤lem je vy콏e코it probl칠my a nejasnosti. Referen캜n칤 콏e코en칤 칰kol콢 bude v쬯y probr치no n치sleduj칤c칤 cvi캜en칤 po deadlinu.

M콢쬰 se st치t, 쬰 v r치mci 칰kolu budete 콏e코it n캩jak칳 technick칳 probl칠m - nap콏. nefunguje knihovna, nevy콏e코iteln치 chyba, nefunguj칤c칤  prost콏ed칤, nem치te data, apod. Ide치ln칤 by tedy bylo tyto v캩ci *zkontrolovat d콏칤ve ne den p콏ed odevzd치n칤m*. Jinak nebude v na코칤 moci, v치m s vy콏e코en칤m probl칠mu pomoct.

== Pot콏ebn칠 n치stroje k 칰kol콢m

칔koly budou ve stejn칠m form치tu jako prob칤h치 pr치ce na cvi캜en칤, tzn. Jupyter notebooky. Na dom치c칤m PC tedy doporu캜ujeme nainstalovat multiplatformn칤 Anacondu pro spr치vu Python bal칤캜ku a vytvo콏it si virtu치ln칤 prost콏ed칤 viz xref:../tutorials/course-tools-introduction#[n치vod]. Pokud nem치te syst칠m Win x64 nebo MacOS, tak se v치m pravd캩podobn캩 nepoda콏칤 vytvo콏it prost콏ed칤 pomoc칤 spec-file a budete muset bal칤캜ky nainstalovat ru캜n캩. Bal칤캜ky se instaluj칤 p콏칤kazem `conda install` viz xref:../tutorials/course-tools-introduction#[n치vod].

=== Seznam pot콏ebn칳ch bal칤캜k콢 k dom치c칤m 칰kol콢m
Je pr콢b캩쬹캩 mezi semestry aktualizov치n. Jedn치 se o seznam instalovateln칳 pomoc칤 n치stroje pip.

* link:../tutorials/env/SVZ-pip-req.txt[Seznam bal칤캜k콢 v txt]

== N치le쬴tosti 칰kolu

Po캜칤tejte pros칤m s t칤m, 쬰 칰kol po v치s bude n캩kdo 캜칤st. Bu캞te tedy tak hodn칤 a zkuste k칩d udr쬺vat 캜ist칳 a 캜iteln칳. Podrobnou dokumentaci nevy쬬dujeme, av코ak ka쬯치 slo쬴t캩j코칤 bu켿ka nebo funkce by m캩la m칤t sv콢j koment치콏. A콘 je v쬯y jasn칠, co dan칳 segment d캩l치 a co je v칳stupem. Pokud nebude k칩d srozumiteln칳, nebude v na코ich sil치ch k n캩mu poskytnout zp캩tnou vazbu.

== Odevzd치n칤 칰kol콢

칔koly odevzd치vejte na FIT Gitlab. Vytvo콏te si priv치tn칤 repozit치콏 a p콏idejte do n캩j u쬴vatele `@zitnyjak`, `@brchlluk`, `@malecada`, `@cahlivoj` a `@novakj67` s rolemi "reporter".
N치sledn캩 *vytvo콏te issue* a p콏i콏a캞te ho na jednoho z n치s.

== Etika dom치c칤ch 칰kol콢

Tak jako je u n치s na fakult캩 zvykem, 칰koly je *nutno vypracov치vat samostatn캩.* Plagi치torstv칤 nebude tolerov치no.

Pokud budete vyu쮂셨at 캜치sti k칩d콢 z internetov칳ch zdroj콢 (nap콏. StackOverflow), *uv치d캩jte v k칩du odkaz na zdrojov칠 vl치kno*. D치le *p콏evzat칳 k칩d okomentujte,* a콘 je vid캩t, 쬰 dan칠 problematice rozum칤te.

== Harmonogram 칰kol콢

Harmonogram 칰kol콢 je p콏edb캩쬹칳. V pr콢b캩hu semestru m콢쬰 b칳t upravov치n.

.Harmonogram 칰kol콢
[cols="2,3,3,9,^2", options="header"]
|===
| 칔kol | Zad치n칤     | Deadline   | T칠ma     | Body
| 1.   | 13. 3. 2020 | 26. 3. 2020 | 游닆{nbsp}
//link:files/1/1_task.ipynb[
M캩콏en칤 nejkrat코칤 vzd치lenosti obd칠ln칤k콢
//]
| 5 (+2)
| 2.   | 27. 3. 2020 | 16. 4. 2020  | 游닆{nbsp}
//link:files/2/2_task.ipynb[
Projektivn칤 transformace
//]
| 6 (+2)
| 3.   | 17. 4. 2020  | 29. 4. 2020 | 游닆{nbsp}
//link:files/3/3_task.ipynb[
V칳po캜et BMI s vyu쬴t칤m dat hloubkov칠ho senzoru
//]
| 7 (+2)
| 4.   | 30. 4. 2020 | 14. 5. 2020   | 游닆{nbsp}
//link:files/4/4_task.ipynb[
V칳po캜et plochy zah콏칤van칠ho spoje s vyu쬴t칤m dat termokamery a RGB kamery
//]
| 8 (+2)
|===