= 3. Dom치c칤 칰koly

V semestru budou postupn캩 zad치ny celkem *4 jednoduch칠 dom치c칤 칰koly*. 칔koly zad치v치me, abychom ov캩콏ili va코e pochopen칤 prob칤ran칠 l치tky. Pro v코echny, kte콏칤 porozum칤 l치tce probran칠 na cvi캜en칤, se jedn치 maxim치ln캩 o dvou hodinovou z치le쬴tost. 칔koly voln캩 *navazuj칤 na 칰lohy z cvi캜en칤*.

칔koly nejsou povinn칠, *tvo콏칤 v코ak p콏es polovinu mo쬹칳ch bod콢 ze semestru* (26 bod콢 z celkov칳ch 50). P콏ipom칤n치me, 쬰 k z칤sk치n칤 z치po캜tu je nutn칠 za cvi캜en칤 z칤skat *minim치ln캩 25 bod콢*, podrobnosti viz sekce xref:../classification/index#[Hodnocen칤].

Na za캜치tku ka쬯칠ho cvi캜en칤 bude prostor na dotazy t칳kaj칤c칤 se aktu치ln칤ho zadan칠ho 칰kolu. C칤lem je vy콏e코it probl칠my a nejasnosti.

M콢쬰 se st치t, 쬰 v r치mci 칰kolu budete 콏e코it n캩jak칳 technick칳 probl칠m - nap콏. nefunguje knihovna, nevy콏e코iteln치 chyba, nefunguj칤c칤  prost콏ed칤, nem치te data, apod. Ide치ln칤 by tedy bylo tyto v캩ci *zkontrolovat d콏칤ve ne den p콏ed odevzd치n칤m*. Jinak nebude v na코칤 moci v치m s vy콏e코en칤m probl칠mu pomoct.

== Pot콏ebn칠 n치stroje k 칰kol콢m

칔koly budou ve stejn칠m form치tu jako prob칤h치 pr치ce na cvi캜en칤, tzn. implementace k칩du v prost콏ed칤 Jupyter Notebook. Ka쬯칠mu byl vytvo콏en repozit치콏 pod vlastn칤m nicknamem, kter칳 bude slou쬴t pro vy콏e코en칤 a odevzd치n칤 칰kol콢. Podrobn칳 n치vod, jak zprovoznit repozit치콏 najdete v *README* v main v캩tvi va코eho repozit치콏e.

== N치le쬴tosti 칰kolu

Po캜칤tejte pros칤m s t칤m, 쬰 칰kol po v치s bude n캩kdo 캜칤st. Bu캞te tedy tak hodn칤 a k칩d udr쬿jte 캜ist칳 a 캜iteln칳. Podrobnou dokumentaci nevy쬬dujeme, av코ak ka쬯치 slo쬴t캩j코칤 bu켿ka nebo funkce mus칤  m칤t sv콢j koment치콏. A콘 je v쬯y jasn칠, co dan칳 segment d캩l치 a co je v칳stupem. Pokud nebude k칩d srozumiteln칳 a okomentovan칳, nebude v na코ich sil치ch k n캩mu poskytnout zp캩tnou vazbu a v extr칠mn칤ch p콏칤padech m콢쬰 b칳t i nehodnotiteln칳. 

== Odevzd치n칤 칰kol콢

V `main` v캩tvi budou p콏ipraveny materi치ly k jednotliv칳m 칰kol콢m, nezapome켿te v쬯y p콏ed vytvo콏en칤m nov칠 v캩tve ud캩lat `pull` mainu. 칔koly se odevzd치vaj칤 pomoc칤 Merge request콢 ve va코em repozit치콏i. Pro ka쬯칳 nov칳 칰kol vytvo콏te v캩tev s n치zvem `hw-XX`, kde XX je 캜칤slo 칰kolu. Pracujte na 칰kolu, commitujte zm캩ny do v캩tve `hw-XX` a pushujte dle libosti. Jakmile 칰kol dokon캜칤te, otev콏ete **merge request** (MR) z va코칤 v캩tve `hw-XX` do va코칤 v캩tve `main`. **NE**p콏i콏azujte Assignee ani Reviewer nikomu ze cvi캜칤c칤ch, roz콏azen칤 bude prov치d캩no a po deadlinu 칰kolu.

== Etika dom치c칤ch 칰kol콢

Tak jako je u n치s na fakult캩 zvykem, 칰koly je *nutno vypracov치vat samostatn캩.* Plagi치torstv칤 nebude tolerov치no. V p콏칤pad캩 *podez콏en칤* bude automaticky 칰kol ohodnocen 0 body. Z치le쮂 pak pouze na studentovi, zda se to zm캩n칤.

Pokud budete vyu쮂셨at 캜치sti k칩d콢 z internetov칳ch zdroj콢 (nap콏. StackOverflow), *uv치d캩jte v k칩du odkaz na zdrojov칠 vl치kno*. D치le *p콏evzat칳 k칩d okomentujte,* a콘 je vid캩t, 쬰 dan칠 problematice rozum칤te.

Pokud bude 칰kol odevzd치n po deadlinu, ten je zpravidla p콏ed p콢lnoc칤 dan칳 den, bude ohodnocen 0 body.

== Harmonogram 칰kol콢

Harmonogram 칰kol콢 je p콏edb캩쬹칳. V pr콢b캩hu semestru m콢쬰 b칳t upravov치n.

// Definice prom캩nn칳ch datum콢
include::../vars.adoc[]

.Harmonogram 칰kol콢
[cols="2,3,3,9,^2", options="header"]
|===
| 칔kol | Zad치n칤     | Deadline   | T칠ma     | Body
| 1.   | {hw1_from} | {hw1_to} | 
M캩콏en칤 nejkrat코칤 vzd치lenosti obd칠ln칤k콢
//游닆{nbsp}link:files/1/1_task.html[M캩콏en칤 nejkrat코칤 vzd치lenosti obd칠ln칤k콢]
| 5 (+2)

| 2.   | {hw2_from} | {hw2_to}  | 
Projektivn칤 transformace
//游닆{nbsp}link:files/2/2_task.html[Projektivn칤 transformace]
| 6 (+2)

| 3.   | {hw3_from}  | {hw3_to} | 
V칳po캜et BMI s vyu쬴t칤m dat hloubkov칠ho senzoru
//游닆{nbsp}link:files/3/3_task.html[V칳po캜et BMI s vyu쬴t칤m dat hloubkov칠ho senzoru]
| 7 (+2)

| 4.   | {hw4_from} | {hw4_to}   | 
V칳po캜et plochy zah콏칤van칠ho spoje s vyu쬴t칤m dat termokamery a RGB kamery
//游닆{nbsp}link:files/4/4_task.html[V칳po캜et plochy zah콏칤van칠ho spoje s vyu쬴t칤m dat termokamery a RGB kamery]
| 8 (+2)
|===
