= 3. Domácí úkoly

V semestru budou postupně zadány celkem *4 jednoduché domácí úkoly*. Úkoly zadáváme, abychom ověřili vaše pochopení probírané látky. Úkoly volně *navazují na úlohy z cvičení*.

Úkoly nejsou povinné, *tvoří však přes polovinu možných bodů ze semestru* (26 bodů z celkových 50). Připomínáme, že k získání zápočtu je nutné za cvičení získat *minimálně 25 bodů*, podrobnosti viz sekce xref:../classification/index#[Hodnocení].

Zadání každého úkolu zveřejňujeme *v pátek po druhém cvičení daného týdne*, aby měly všechny skupiny stejných *14 dní* na vypracování. Úkol je na obou cvičeních představen, materiály jsou však pro všechny dostupné od stejného okamžiku.

Na začátku každého cvičení bude prostor na dotazy týkající se aktuálního zadaného úkolu. Cílem je vyřešit problémy a nejasnosti.

Může se stát, že v rámci úkolu budete řešit nějaký technický problém - např. nefunguje knihovna, nevyřešitelná chyba, nefungující  prostředí, nemáte data, apod. Ideální by tedy bylo tyto věci *zkontrolovat dříve než den před odevzdáním*. Jinak nebude v naší moci vám s vyřešením problému pomoct.

== Potřebné nástroje k úkolům

Úkoly budou ve stejném formátu jako probíhá práce na cvičení, tzn. implementace kódu v prostředí Jupyter Notebook. Každému byl vytvořen repozitář pod vlastním nicknamem, který bude sloužit pro vyřešení a odevzdání úkolů. Podrobný návod, jak zprovoznit repozitář najdete v *README* v main větvi vašeho repozitáře.

== Náležitosti úkolu

Počítejte prosím s tím, že úkol po vás bude někdo číst. Buďte tedy tak hodní a kód udržujte čistý a čitelný. Podrobnou dokumentaci nevyžadujeme, avšak každá složitější buňka nebo funkce musí  mít svůj komentář. Ať je vždy jasné, co daný segment dělá a co je výstupem. Pokud nebude kód srozumitelný a okomentovaný, nebude v našich silách k němu poskytnout zpětnou vazbu a v extrémních případech může být i nehodnotitelný. 

== Odevzdání úkolů

V `main` větvi budou připraveny materiály k jednotlivým úkolům, nezapomeňte vždy před vytvořením nové větve udělat `pull` mainu. Úkoly se odevzdávají pomocí Merge requestů ve vašem repozitáři. Pro každý nový úkol vytvořte větev s názvem `hw-XX`, kde XX je číslo úkolu. Pracujte na úkolu, commitujte změny do větve `hw-XX` a pushujte dle libosti. Jakmile úkol dokončíte, otevřete **merge request** (MR) z vaší větve `hw-XX` do vaší větve `main`. **NE**přiřazujte Assignee ani Reviewer nikomu ze cvičících, rozřazení bude prováděno až po deadlinu úkolu.

== Etika domácích úkolů

Tak jako je u nás na fakultě zvykem, úkoly je *nutno vypracovávat samostatně.* Plagiátorství nebude tolerováno. V případě *podezření* bude automaticky úkol ohodnocen 0 body. Záleží pak pouze na studentovi, zda se to změní.

Pokud budete využívat části kódů z internetových zdrojů (např. StackOverflow), *uvádějte v kódu odkaz na zdrojové vlákno*. Dále *převzatý kód okomentujte,* ať je vidět, že dané problematice rozumíte.

Pokud bude úkol odevzdán po deadlinu, ten je zpravidla před půlnocí daný den, bude ohodnocen 0 body.

== Harmonogram úkolů

Harmonogram úkolů je předběžný. V průběhu semestru může být upravován.

// Definice proměnných datumů
include::../vars.adoc[]

.Harmonogram úkolů
[cols="2,3,3,9,^2", options="header"]
|===
| Úkol | Zadání     | Deadline   | Téma     | Body
| 1.   | {hw1_from} | {hw1_to} | 
Měření nejkratší vzdálenosti obdélníků
//📜{nbsp}link:files/1/1_task.html[Měření nejkratší vzdálenosti obdélníků]
| 5 (+2)

| 2.   | {hw2_from} | {hw2_to}  | 
Projektivní transformace
//📜{nbsp}link:files/2/2_task.html[Projektivní transformace]
| 6 (+2)

| 3.   | {hw3_from}  | {hw3_to} | 
Výpočet BMI s využitím dat hloubkového senzoru
//📜{nbsp}link:files/3/3_task.html[Výpočet BMI s využitím dat hloubkového senzoru]
| 7 (+2)

| 4.   | {hw4_from} | {hw4_to}   | 
Výpočet plochy zahřívaného spoje s využitím dat termokamery a RGB kamery
//📜{nbsp}link:files/4/4_task.html[Výpočet plochy zahřívaného spoje s využitím dat termokamery a RGB kamery]
| 8 (+2)
|===
