= 2. Cvi캜en칤

Zm캩na programu vyhrazena. Cvi캜en칤 se v pr콢b캩hu budou m캩nit / p콏izp콢sobovat pr콢b캩hu semestru.

// Definice prom캩nn칳ch datum콢
include::../vars.adoc[]

.Harmonogram cvi캜en칤
[width=100%, cols="^1,2,5,5,^1", options="header"]
|====
| # | Datum | T칠ma | Soubory | Body

| 1.
| {dc01}
| Sezn치men칤 s n치stroji
| 游닀{nbsp}link:files/1/bi-svz-01-cviceni-uvod.pdf[칔vod{nbsp}do{nbsp}p콏edm캩tu],
游닀{nbsp}link:../manuals/lab-equipment.html[Z치sady{nbsp}pr치ce{nbsp}s{nbsp}vybaven칤m]
| 2

| 2.
| {dc02}
| Pr치ce s kamerami a z치klady zpracov치n칤 obrazu
| 游닆{nbsp}link:files/2/camera-introduction.html[Pr치ce{nbsp}s{nbsp}kamerami],
游닆{nbsp}link:files/2/improutils-introduction.html[Z치klady{nbsp}zpracov치n칤{nbsp}obrazu]
| 2

| 3.
| {dc03}
| Vady optiky, kalibrace kamery
| 游닆{nbsp}link:files/3/lens-defects.html[Vady{nbsp}optiky]
游닆{nbsp}link:files/3/camera-calibration.html[Kalibrace{nbsp}kamery]
| 2

| 4.
| {dc04}
| Segmentace obrazu
| 游닆{nbsp}link:files/4/segmentation-and-measuring.html[Z치klady segmentace],
游닆{nbsp}link:files/4/segmentation-objects-count.html[Segmentace{nbsp}-{nbsp}po캜칤t치n칤{nbsp}objekt콢],
| 2

| 5.
| {dc05}
| Vyu쬴t칤 sv캩tel
| 游닆{nbsp}link:files/5/segmentation-fit-ocr.html[Segmentace{nbsp}-{nbsp}OCR{nbsp}textu],
游닆{nbsp}link:files/5/mono_segmentation.html[Segmentace{nbsp}-{nbsp}Monochromatick치{nbsp}kamera]
| 2

| 6.
| {dc06}
| Perspektiva obrazu
| 游닆{nbsp}link:files/6/perspective-measuring-length.html[Perspektiva{nbsp}-{nbsp}m캩콏en칤{nbsp}vzd치lenosti],
游닆{nbsp}link:files/6/perspective-measuring-height.html[Perspektiva{nbsp}-{nbsp}m캩콏en칤{nbsp}v칳코ky]
| 2

| 7.
| {dc07}
| Pr치ce s hloubkovou kamerou
| 游닆{nbsp}link:files/7/depth-camera.html[Hloubkov칠{nbsp}senzory]
//游닆{nbsp}link:files/7/depth-collisions.html[Hloubkov칠{nbsp}senzory{nbsp}-{nbsp}detekce{nbsp}koliz칤]
| 2

| 8.
| {dc08}
| 콎치dkov칠 kamery
| 游닆{nbsp}link:files/8/linescan-qr-reader.html[Detekce{nbsp}a{nbsp}캜ten칤{nbsp}datamatrix{nbsp}a{nbsp}QR{nbsp}k칩d콢]
| 2

| 9.
| {dc09}
| Techniky transformace
| 游닆{nbsp}link:files/9/fourier-transform.html[Detekce{nbsp}defekt콢{nbsp}pomoc칤{nbsp}Fourierovy{nbsp}transformace]
| 2

| 10.
| {dc10}
| Perspektiva obrazu, 360춿 objektivy
| 游닆{nbsp}link:files/10/perspective-cart-polar-system.html[Perspektiva{nbsp}-{nbsp}pol치rn칤{nbsp}sou콏adn칳{nbsp}syst칠m], 游닆{nbsp}link:files/10/perspective-treads-measurement.html[Perspektiva{nbsp}-{nbsp}m캩콏en칤{nbsp}z치vit콢]
| 2

| 11.
| {dc11}
| Z치klady m캩콏en칤 s termokamerou
| 游닆{nbsp}link:files/11/filters/filters.html[Termokamery{nbsp}-{nbsp}z치klady{nbsp}m캩콏en칤]
//游닆{nbsp}link:files/11/face-detection.html[Detekce{nbsp}obli캜eje{nbsp}pomoci{nbsp}termokamery]
| 2

| 12.
| {dc12}
| Klasifikace obrazu, detekce objekt콢
| 游닆{nbsp}link:files/12/object-classification.html[Klasifikace{nbsp}objekt콢{nbsp}-{nbsp}tvarov칠{nbsp}charakteristiky],
游닆{nbsp}link:files/12/face-detection-description.html[Detekce{nbsp}obli캜ej콢]
| 2
|====

== Cvi캜en칤 v laborato콏i ImproLab

Pro pr치ci na cvi캜en칤 v na코칤 laborato콏i budeme vyu쮂셨at n캩kolik n치stroj콢.

* https://www.anaconda.com/[Anaconda] - multiplatformn칤 spr치vce bal칤캜k콢 pro jazyk Python.
* http://jupyter.org/[Jupyter Notebook] - webov치 aplikace k rychl칠mu prototypov치n칤 algoritm콢 v Pythonu.
* https://www.baslerweb.com/en/products/software/basler-pylon-camera-software-suite/[Pylon] - software a SDK slou쮂셖칤 pro pr치ci s kamerami od firmy Basler.

Volba jazyka Python m콢쬰 b칳t pro n캩kter칠 z v치s nepochopiteln치, zvl치코t캩 kdy v bakal치콏sk칠m programu nen칤 povinn칳. D콢vod je v코ak prost칳 - jazyk Python je v tuto chv칤li nejvyu쮂셨an캩j코칤 pro obory data science a computer vision. V칳voj v Pythonu je rychl칳, jednoduch칳 a velmi efektivn칤. Existuje velk칠 mno쬽tv칤 knihoven, n치vod콢 a p콏ipraven칳ch k칩d콢, kter칠 v ostatn칤ch jazyc칤ch nemaj칤 obdoby. Nav칤c, pokud byste se cht캩li zpracov치n칤 obrazu d치le v캩novat, stejn캩 byste pravd캩podobn캩 skon캜ili pr치v캩 s Pythonem. Ti z v치s, kte콏칤 budou pokra캜ovat v magistersk칠m programu Znalostn칤ho in쬰n칳rstv칤, si Python a Jupyter Notebooky hojn캩 u쬴j칤 i pozd캩ji.

C칤lem tohoto kurzu v코ak nen칤 vyu캜ovat jazyk Python, n칳br zam캩콏it se pr치v캩 na kl칤캜ov칠 metody a algoritmy zpracov치n칤 obrazu. Python je jen nejvhodn캩j코칤 n치stroj, jak tento c칤l bezbolestn캩 naplnit a z치rove켿 toho uk치zat co nejv칤ce.

Na코e pr치ce se nebude skl치dat ani tak z programov치n칤 v Pythonu, ale p콏ev치쬹캩 z vol치n칤 ji hotov칳ch metod a vyu쮂셨치n칤 rozhran칤 (nap콏. OpenCV). Uvid칤te sami, 쬰 v캩t코ina 칰kol콢, kter칠 budeme 콏e코it, budou p콏edp콏ipraven칠 a vysta캜칤me si tedy se z치kladn칤 syntax칤 jazyka. Mnohem d콢le쬴t캩j코칤 je porozum캩n칤 kontextu probl칠mu a n치vrh algoritm콢/metod k jeho vy콏e코en칤.

Stru캜n칠 z치klady Pythonu lze nal칠zt v notebooku link:../manuals/python-introduction.html[Z치klady syntaxe v Pythonu]. Pro hlub코칤 pozn치n칤 existuje t콏eba kurz v 캜e코tin캩 od https://naucse.python.cz/course/pyladies/[PyLadies].
캛asto vyu쮂셨an칠 kl치vesov칠 zkratky v Jupyter notebooku jsou pops치ny xref:../manuals/jupyter-notebook-cheat-sheet.pdf[zde].

== Odevzd치v치n칤 cvi캜en칤

V코echny praktick칠 칰lohy, kter치 se *vypracov치vaj칤 v laborato콏i*, se odevzd치vaj칤 pouze *formou uk치zky cvi캜칤c칤m*. Doporu캜ujeme , abyste si vypracovan치 cvi캜en칤 z치lohovali k sob캩 na Gitlab, abyste se z nich mohli u캜it na praktickou zkou코ku. 

Pokud na cvi캜en칤 chyb칤te, nen칤 mo쬹칠 z칤skat body zp캩tn캩 ani si jinak body doplnit!