= 2. Cvičení

Změna programu vyhrazena. Cvičení se v průběhu budou měnit / přizpůsobovat průběhu semestru.

// Definice proměnných datumů
include::../vars.adoc[]

.Harmonogram cvičení
[width=100%, cols="^1,4,5,5,1,^4", options="header"]
|====
| # | Datum | Téma | Soubory | Body | Cvičící

| 1.
| {dc01}
| Seznámení s nástroji
| 📖{nbsp}link:files/1/bi-svz-01-cviceni-uvod.pdf[Úvod{nbsp}do{nbsp}předmětu],
📖{nbsp}link:../manuals/lab-equipment.html[Zásady{nbsp}práce{nbsp}s{nbsp}vybavením]
| 2
| J. Frommová, J. Hrabáková

| 2.
| {dc02}
| Práce s kamerami a základy zpracování obrazu
| 📜{nbsp}link:files/2/camera-introduction.html[Práce{nbsp}s{nbsp}kamerami],
📜{nbsp}link:files/2/improutils-introduction.html[Základy{nbsp}zpracování{nbsp}obrazu]
| 2
| J. Hrabáková, D. Pilař

| 3.
| {dc03}
| Vady optiky, kalibrace kamery
| 📜{nbsp}link:files/3/lens-defects.html[Vady{nbsp}optiky]
📜{nbsp}link:files/3/camera-calibration.html[Kalibrace{nbsp}kamery]
| 2
| J. Hrabáková, D. Kramný

| 4.
| {dc04}
| Segmentace obrazu
| 📜{nbsp}link:files/4/segmentation-and-measuring.html[Základy segmentace],
📜{nbsp}link:files/4/segmentation-objects-count.html[Segmentace{nbsp}-{nbsp}počítání{nbsp}objektů],
| 2
| J. Hrabáková, O. Juřík

| 5.
| {dc05}
| Využití světel
| 📜{nbsp}link:files/5/segmentation-fit-ocr.html[Segmentace{nbsp}-{nbsp}OCR{nbsp}textu],
📜{nbsp}link:files/5/mono_segmentation.html[Segmentace{nbsp}-{nbsp}Monochromatická{nbsp}kamera]
| 2
| J. Hrabáková, D. Kramný

| 6.
| {dc06}
| Perspektiva obrazu
| 📜{nbsp}link:files/6/perspective-measuring-length.html[Perspektiva{nbsp}-{nbsp}měření{nbsp}vzdálenosti],
📜{nbsp}link:files/6/perspective-measuring-height.html[Perspektiva{nbsp}-{nbsp}měření{nbsp}výšky]
| 2
| J. Hrabáková, V. Pospíšil

| 7.
| {dc07}
| Práce s hloubkovou kamerou
| 📜{nbsp}link:files/7/depth_camera.html[Hloubkové{nbsp}senzory]
//📜{nbsp}link:files/7/depth-collisions.html[Hloubkové{nbsp}senzory{nbsp}-{nbsp}detekce{nbsp}kolizí]
| 2
| J. Hrabáková, V. Pospíšil

| 8.
| {dc08}
| Perspektiva obrazu, 360° objektivy
| 📜{nbsp}link:files/10/perspective-cart-polar-system.html[Perspektiva{nbsp}-{nbsp}polární{nbsp}souřadný{nbsp}systém], 📜{nbsp}link:files/10/perspective-treads-measurement.html[Perspektiva{nbsp}-{nbsp}měření{nbsp}závitů]
| 2
| J. Hrabáková, J. Frommová

| 9.
| {dc09}
| Řádkové kamery
| 📜{nbsp}link:files/8/linescan-qr-reader.html[Detekce{nbsp}a{nbsp}čtení{nbsp}datamatrix{nbsp}a{nbsp}QR{nbsp}kódů]
| 2
| J. Hrabáková, D. Pilař

| 10.
| {dc10}
| Techniky transformace
| 📜{nbsp}link:files/9/fourier-transform.html[Detekce{nbsp}defektů{nbsp}pomocí{nbsp}Fourierovy{nbsp}transformace]
| 2
| J. Hrabáková, T. Nguyen

| 11.
| {dc11}
| Základy měření s termokamerou
| 📜{nbsp}link:files/11/filters/filters.html[Termokamery{nbsp}-{nbsp}základy{nbsp}měření]
//📜{nbsp}link:files/11/face-detection.html[Detekce{nbsp}obličeje{nbsp}pomoci{nbsp}termokamery]
| 2
| J. Hrabáková, T. Nguyen

| 12.
| {dc12}
| Klasifikace obrazu, detekce objektů
| 📜{nbsp}link:files/12/object-classification.html[Klasifikace{nbsp}objektů{nbsp}-{nbsp}tvarové{nbsp}charakteristiky],
📜{nbsp}link:files/12/face-detection-description.html[Detekce{nbsp}obličejů]
| 2
| J. Hrabáková, O. Juřík
|====

== Cvičení v laboratoři ImproLab

Pro práci na cvičení v naší laboratoři budeme využívat několik nástrojů.

* https://www.anaconda.com/[Anaconda] - multiplatformní správce balíčků pro jazyk Python.
* http://jupyter.org/[Jupyter Notebook] - webová aplikace k rychlému prototypování algoritmů v Pythonu.
* https://www.baslerweb.com/en/products/software/basler-pylon-camera-software-suite/[Pylon] - software a SDK sloužící pro práci s kamerami od firmy Basler.

Volba jazyka Python může být pro některé z vás nepochopitelná, zvláště když v bakalářském programu není povinný. Důvod je však prostý - jazyk Python je v tuto chvíli nejvyužívanější pro obory data science a computer vision. Vývoj v Pythonu je rychlý, jednoduchý a velmi efektivní. Existuje velké množství knihoven, návodů a připravených kódů, které v ostatních jazycích nemají obdoby. Navíc, pokud byste se chtěli zpracování obrazu dále věnovat, stejně byste pravděpodobně skončili právě s Pythonem. Ti z vás, kteří budou pokračovat v magisterském programu Znalostního inženýrství, si Python a Jupyter Notebooky hojně užijí i později.

Cílem tohoto kurzu však není vyučovat jazyk Python, nýbrž zaměřit se právě na klíčové metody a algoritmy zpracování obrazu. Python je jen nejvhodnější nástroj, jak tento cíl bezbolestně naplnit a zároveň toho ukázat co nejvíce.

Naše práce se nebude skládat ani tak z programování v Pythonu, ale převážně z volání již hotových metod a využívání rozhraní (např. OpenCV). Uvidíte sami, že většina úkolů, které budeme řešit, budou předpřipravené a vystačíme si tedy se základní syntaxí jazyka. Mnohem důležitější je porozumění kontextu problému a návrh algoritmů/metod k jeho vyřešení.

Stručné základy Pythonu lze nalézt v notebooku link:../manuals/python-introduction.html[Základy syntaxe v Pythonu]. Pro hlubší poznání existuje třeba kurz v češtině od https://naucse.python.cz/course/pyladies/[PyLadies].
Často využívané klávesové zkratky v Jupyter notebooku jsou popsány xref:../manuals/jupyter-notebook-cheat-sheet.pdf[zde].

== Odevzdávání cvičení

Všechny praktické úlohy, která se *vypracovávají v laboratoři*, se odevzdávají pouze *formou ukázky cvičícím*. Doporučujeme , abyste si vypracovaná cvičení zálohovali k sobě na Gitlab, abyste se z nich mohli učit na praktickou zkoušku. 

Pokud na cvičení chybíte, není možné získat body zpětně ani si jinak body doplnit!