= Virtuální prostředí

V učebně máme nainstalovaný systém Windows, všechny popsané kroky se tedy budou týkat tohoto systému. Instalace a kroky na Linuxu či Macu jsou však také popsány. 

K naší práci budeme potřebovat několik balíčku, které je potřeba nainstalovat do virtuálního prostředí. Abychom nám usnadnily život, je možné při vytváření virtuálního prostředí specifikovat soubor _spec-file.txt_, který obsahuje seznam potřebných balíčků pro tento kurz (viz jednotlivé soubory pro různé operační systémy níže). Ty se následně nainstalují při vytváření virtuálního prostředí. 

Detaily ke správě prostředí lze nalézt https://conda.io/docs/user-guide/tasks/manage-environments.html[zde], detaily k instalaci balíčků https://conda.io/docs/user-guide/tasks/manage-pkgs.html[zde].

== Postup na cvičení

* Zkontrolujte, zda je u vás na PC nainstalovaná Anaconda.
* Zapněte si `Anaconda Prompt`, ve kterém je možné využívat Python interpreter, instalovat balíčky a přepínat/modifikovat virtuální prostředí.
* Zkontrolujte, jaké u vás existují virtuální prostředí 
** `conda env list`
* Pokud v seznamu *NENÍ* prostředí SVZ:
** Přidejte cestu s vytvořeným virtuální prostředí do Anacondy. 
*** `conda config --append envs_dirs D:\env`
* Vyzkoušejte:
** `conda activate SVZ`
* Pokud stále něco nepůjde, kontaktujte učitele :)


== Postup doma

* Zkontrolujte, zda je u vás na PC nainstalovaná Anaconda. Jinak si ji https://www.anaconda.com/download[stáhněte] a nainstalujte (vždy nejnovější verzi pro Python 3.7).
* Zapněte si `Anaconda Prompt`, ve kterém je možné využívat Python interpreter, instalovat balíčky a přepínat/modifikovat virtuální prostředí.

* Zvolte správný spec-file pro váš operační systém
** Windows 10 (x64): link:../env/SVZ-spec-file-win64.txt[SVZ-spec-file-win64]
** Linux Ubuntu (x64): link:../env/SVZ-spec-file-linux-ubuntu.txt[SVZ-spec-file-linux-ubuntu]
** macOS (x64): link:../env/SVZ-spec-file-darwin.txt[SVZ-spec-file-darwin]
* Vytvořte prostředí SVZ pomocí spec-file  takto:
** `conda create --name SVZ --file <cesta k SVZ-spec-file-XXX.txt>`
* Aktivujte vytvořené virtuální prostředí
** `activate SVZ`
* Doinstalujte potřebné knihovny pipem pomocí link:../env/SVZ-pip-req.txt[SVZ-pip-req] takto:
** `pip install -r <cesta k SVZ-pip-req.txt>`


== Důležité

* Před každým cvičením/úkolem je nutné zkontrolovat zda nepracujete ve výchozím prostředí (base). Přepnutí do prostředí SVZ:
** `conda activate SVZ`
* S aktivovaným prostředím spusťte Jupyter notebook ve složce se soubory ke kurzu
** `jupyter notebook <cesta k souborum kurzu>` 
* Otevřete úvodní notebook link:../files/1/python-introduction.ipynb[Seznámení s jazykem Python] a zkontrolujte, zda všechny úvodní importy proběhnou bez problémů. 
** Pokud uvidíte hlášky typu `ImportError: No module named cv2`, musí se daný balíček doinstalovat pomocí `conda install`. V tom případě kontaktujte učitele.


=== Poznámky

Výpis všech virtuálních prostředí lze provést pomocí `conda env list`, výpis balíčku v aktuálním prostředí `conda list`. Deaktivace aktuálního prostředí pomocí `conda deactivate`.  V případě, že chcete nějaké prostředí odstranit, tak `conda env remove --name <nazev>`. Dobrým zvykem je neinstalovat balíčky globálně (do výchozího base prostředí), ale pro každý projekt vytvořit nové virtuální prostředí. Další detaily ke správě prostředí lze nalézt https://conda.io/docs/user-guide/tasks/manage-environments.html[zde].


=== Tvorba nového virtuálního prostředí (pro admina) 

* Stáhnout soubor link:../env/SVZ-spec-file-win64.txt[SVZ-spec-file-win64] a vytvořit virtuální prostředí s balíčky nutnými pro tento kurz. 
* Virtuální prostředí se vytváří na disku D:
** `conda create --prefix D:\env\SVZ --file <cesta k spec-file.txt>`
