= 7. Showroom

Sekce odkazuje na ukázky zdrojových kódů podrobněji vysvětlující algoritmy nebo principy strojového vidění a zpracování obrazu.

Uveřejnění ukázky studenta si zaslouží *body aktivity*.

Zdrojové kódy ukázek jsou po naklonování repozitáře umístěny ve složce `showroom`.

== Ukázky
* xref:adaptive_thresholding/index.html[Adaptivní prahování] (`@novakj67`)
** Cílem ukázky je ukázat práci algoritmu pro adaptivní prahování pomocí Gaussova jádra.

* xref:histogram_of_oriented_gradients/index.html[Histogram orientovaných gradientů (HoG)] (`@masekda4`)
** Cílem ukázky je ukázat práci algoritmu HoG pro zisk příznaků pro úlohu klasifikace.

* xref:morfologie/index.html[Morfologie] (`@novakj67`)
** Ukázka je podpůrným materiálem k rozšířenému videomateriálu přednášky - xref:../lectures/index.html[Morfologie a tvarové charakteristiky].

* xref:illumination/index.html[Volba vhodného osvětlení v kombinaci s kamerou] (`@kramnda1`)
** Cílem ukázky je zdůraznit důležitost volby vhodného osvětlení a kamery. Zároveň jsou představena světla se kterými je možnost setkat se při cvičení. Každé světlo je stručně popsáno a jsou uvedeny konkrétní informace o světle samotném, např. jeho vlnová délka.

* xref:monadic_operations/index.html[Monadické operace] (`@kramnda1`)
**  Interaktivní demonstrace úpravy jasu a kontastu, gamma korekce, ekvalizace histogramu a CLAHE. Slouží jako podpůrný materiál k přednášce - xref:../lectures/index.html[Předzpracování obrazu - Transformace a korekce].
